// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: backend_core_v1.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace NUHS.Backend {
  public static partial class BackendCoreServiceV1
  {
    static readonly string __ServiceName = "BackendCoreServiceV1";

    static readonly grpc::Marshaller<global::NUHS.Backend.BackendPingRequestV1> __Marshaller_BackendPingRequestV1 = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::NUHS.Backend.BackendPingRequestV1.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::NUHS.Backend.BackendPingResponseV1> __Marshaller_BackendPingResponseV1 = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::NUHS.Backend.BackendPingResponseV1.Parser.ParseFrom);

    static readonly grpc::Method<global::NUHS.Backend.BackendPingRequestV1, global::NUHS.Backend.BackendPingResponseV1> __Method_Ping = new grpc::Method<global::NUHS.Backend.BackendPingRequestV1, global::NUHS.Backend.BackendPingResponseV1>(
        grpc::MethodType.Unary,
        __ServiceName,
        "Ping",
        __Marshaller_BackendPingRequestV1,
        __Marshaller_BackendPingResponseV1);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::NUHS.Backend.BackendCoreV1Reflection.Descriptor.Services[0]; }
    }

    /// <summary>Client for BackendCoreServiceV1</summary>
    public partial class BackendCoreServiceV1Client : grpc::ClientBase<BackendCoreServiceV1Client>
    {
      /// <summary>Creates a new client for BackendCoreServiceV1</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public BackendCoreServiceV1Client(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for BackendCoreServiceV1 that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public BackendCoreServiceV1Client(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected BackendCoreServiceV1Client() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected BackendCoreServiceV1Client(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual global::NUHS.Backend.BackendPingResponseV1 Ping(global::NUHS.Backend.BackendPingRequestV1 request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return Ping(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::NUHS.Backend.BackendPingResponseV1 Ping(global::NUHS.Backend.BackendPingRequestV1 request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_Ping, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::NUHS.Backend.BackendPingResponseV1> PingAsync(global::NUHS.Backend.BackendPingRequestV1 request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return PingAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::NUHS.Backend.BackendPingResponseV1> PingAsync(global::NUHS.Backend.BackendPingRequestV1 request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_Ping, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override BackendCoreServiceV1Client NewInstance(ClientBaseConfiguration configuration)
      {
        return new BackendCoreServiceV1Client(configuration);
      }
    }

  }
}
#endregion
