// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: ultrasound_profile_v1.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace NUHS.Backend {
  public static partial class UltrasoundProfileServiceV1
  {
    static readonly string __ServiceName = "UltrasoundProfileServiceV1";

    static readonly grpc::Marshaller<global::NUHS.Backend.UltrasoundProfileListRequestV1> __Marshaller_UltrasoundProfileListRequestV1 = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::NUHS.Backend.UltrasoundProfileListRequestV1.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::NUHS.Backend.UltrasoundProfileListV1> __Marshaller_UltrasoundProfileListV1 = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::NUHS.Backend.UltrasoundProfileListV1.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::NUHS.Backend.UltrasoundProfileGetRequestV1> __Marshaller_UltrasoundProfileGetRequestV1 = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::NUHS.Backend.UltrasoundProfileGetRequestV1.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::NUHS.Backend.UltrasoundProfileV1> __Marshaller_UltrasoundProfileV1 = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::NUHS.Backend.UltrasoundProfileV1.Parser.ParseFrom);

    static readonly grpc::Method<global::NUHS.Backend.UltrasoundProfileListRequestV1, global::NUHS.Backend.UltrasoundProfileListV1> __Method_List = new grpc::Method<global::NUHS.Backend.UltrasoundProfileListRequestV1, global::NUHS.Backend.UltrasoundProfileListV1>(
        grpc::MethodType.Unary,
        __ServiceName,
        "List",
        __Marshaller_UltrasoundProfileListRequestV1,
        __Marshaller_UltrasoundProfileListV1);

    static readonly grpc::Method<global::NUHS.Backend.UltrasoundProfileGetRequestV1, global::NUHS.Backend.UltrasoundProfileV1> __Method_Get = new grpc::Method<global::NUHS.Backend.UltrasoundProfileGetRequestV1, global::NUHS.Backend.UltrasoundProfileV1>(
        grpc::MethodType.Unary,
        __ServiceName,
        "Get",
        __Marshaller_UltrasoundProfileGetRequestV1,
        __Marshaller_UltrasoundProfileV1);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::NUHS.Backend.UltrasoundProfileV1Reflection.Descriptor.Services[0]; }
    }

    /// <summary>Client for UltrasoundProfileServiceV1</summary>
    public partial class UltrasoundProfileServiceV1Client : grpc::ClientBase<UltrasoundProfileServiceV1Client>
    {
      /// <summary>Creates a new client for UltrasoundProfileServiceV1</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public UltrasoundProfileServiceV1Client(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for UltrasoundProfileServiceV1 that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public UltrasoundProfileServiceV1Client(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected UltrasoundProfileServiceV1Client() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected UltrasoundProfileServiceV1Client(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual global::NUHS.Backend.UltrasoundProfileListV1 List(global::NUHS.Backend.UltrasoundProfileListRequestV1 request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return List(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::NUHS.Backend.UltrasoundProfileListV1 List(global::NUHS.Backend.UltrasoundProfileListRequestV1 request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_List, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::NUHS.Backend.UltrasoundProfileListV1> ListAsync(global::NUHS.Backend.UltrasoundProfileListRequestV1 request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return ListAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::NUHS.Backend.UltrasoundProfileListV1> ListAsync(global::NUHS.Backend.UltrasoundProfileListRequestV1 request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_List, null, options, request);
      }
      public virtual global::NUHS.Backend.UltrasoundProfileV1 Get(global::NUHS.Backend.UltrasoundProfileGetRequestV1 request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return Get(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::NUHS.Backend.UltrasoundProfileV1 Get(global::NUHS.Backend.UltrasoundProfileGetRequestV1 request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_Get, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::NUHS.Backend.UltrasoundProfileV1> GetAsync(global::NUHS.Backend.UltrasoundProfileGetRequestV1 request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::NUHS.Backend.UltrasoundProfileV1> GetAsync(global::NUHS.Backend.UltrasoundProfileGetRequestV1 request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_Get, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override UltrasoundProfileServiceV1Client NewInstance(ClientBaseConfiguration configuration)
      {
        return new UltrasoundProfileServiceV1Client(configuration);
      }
    }

  }
}
#endregion
