// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: sidecar_core_v1.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace NUHS.Sidecar {
  public static partial class SidecarCoreServiceV1
  {
    static readonly string __ServiceName = "SidecarCoreServiceV1";

    static readonly grpc::Marshaller<global::NUHS.Sidecar.SidecarPingRequestV1> __Marshaller_SidecarPingRequestV1 = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::NUHS.Sidecar.SidecarPingRequestV1.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::NUHS.Sidecar.SidecarPingResponseV1> __Marshaller_SidecarPingResponseV1 = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::NUHS.Sidecar.SidecarPingResponseV1.Parser.ParseFrom);

    static readonly grpc::Method<global::NUHS.Sidecar.SidecarPingRequestV1, global::NUHS.Sidecar.SidecarPingResponseV1> __Method_Ping = new grpc::Method<global::NUHS.Sidecar.SidecarPingRequestV1, global::NUHS.Sidecar.SidecarPingResponseV1>(
        grpc::MethodType.Unary,
        __ServiceName,
        "Ping",
        __Marshaller_SidecarPingRequestV1,
        __Marshaller_SidecarPingResponseV1);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::NUHS.Sidecar.SidecarCoreV1Reflection.Descriptor.Services[0]; }
    }

    /// <summary>Client for SidecarCoreServiceV1</summary>
    public partial class SidecarCoreServiceV1Client : grpc::ClientBase<SidecarCoreServiceV1Client>
    {
      /// <summary>Creates a new client for SidecarCoreServiceV1</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public SidecarCoreServiceV1Client(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for SidecarCoreServiceV1 that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public SidecarCoreServiceV1Client(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected SidecarCoreServiceV1Client() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected SidecarCoreServiceV1Client(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual global::NUHS.Sidecar.SidecarPingResponseV1 Ping(global::NUHS.Sidecar.SidecarPingRequestV1 request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return Ping(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::NUHS.Sidecar.SidecarPingResponseV1 Ping(global::NUHS.Sidecar.SidecarPingRequestV1 request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_Ping, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::NUHS.Sidecar.SidecarPingResponseV1> PingAsync(global::NUHS.Sidecar.SidecarPingRequestV1 request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return PingAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::NUHS.Sidecar.SidecarPingResponseV1> PingAsync(global::NUHS.Sidecar.SidecarPingRequestV1 request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_Ping, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override SidecarCoreServiceV1Client NewInstance(ClientBaseConfiguration configuration)
      {
        return new SidecarCoreServiceV1Client(configuration);
      }
    }

  }
}
#endregion
