// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: ultrasound_capture_v1.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace NUHS.Sidecar {
  public static partial class UltrasoundCaptureServiceV1
  {
    static readonly string __ServiceName = "UltrasoundCaptureServiceV1";

    static readonly grpc::Marshaller<global::NUHS.Sidecar.UltrasoundCaptureSetupRequestV1> __Marshaller_UltrasoundCaptureSetupRequestV1 = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::NUHS.Sidecar.UltrasoundCaptureSetupRequestV1.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::NUHS.Sidecar.UltrasoundCaptureSetupResponseV1> __Marshaller_UltrasoundCaptureSetupResponseV1 = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::NUHS.Sidecar.UltrasoundCaptureSetupResponseV1.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::NUHS.Sidecar.UltrasoundCaptureRequestV1> __Marshaller_UltrasoundCaptureRequestV1 = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::NUHS.Sidecar.UltrasoundCaptureRequestV1.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::NUHS.Sidecar.UltrasoundCaptureFrameV1> __Marshaller_UltrasoundCaptureFrameV1 = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::NUHS.Sidecar.UltrasoundCaptureFrameV1.Parser.ParseFrom);

    static readonly grpc::Method<global::NUHS.Sidecar.UltrasoundCaptureSetupRequestV1, global::NUHS.Sidecar.UltrasoundCaptureSetupResponseV1> __Method_Setup = new grpc::Method<global::NUHS.Sidecar.UltrasoundCaptureSetupRequestV1, global::NUHS.Sidecar.UltrasoundCaptureSetupResponseV1>(
        grpc::MethodType.Unary,
        __ServiceName,
        "Setup",
        __Marshaller_UltrasoundCaptureSetupRequestV1,
        __Marshaller_UltrasoundCaptureSetupResponseV1);

    static readonly grpc::Method<global::NUHS.Sidecar.UltrasoundCaptureRequestV1, global::NUHS.Sidecar.UltrasoundCaptureFrameV1> __Method_Stream = new grpc::Method<global::NUHS.Sidecar.UltrasoundCaptureRequestV1, global::NUHS.Sidecar.UltrasoundCaptureFrameV1>(
        grpc::MethodType.ServerStreaming,
        __ServiceName,
        "Stream",
        __Marshaller_UltrasoundCaptureRequestV1,
        __Marshaller_UltrasoundCaptureFrameV1);

    static readonly grpc::Method<global::NUHS.Sidecar.UltrasoundCaptureRequestV1, global::NUHS.Sidecar.UltrasoundCaptureFrameV1> __Method_SingleFrame = new grpc::Method<global::NUHS.Sidecar.UltrasoundCaptureRequestV1, global::NUHS.Sidecar.UltrasoundCaptureFrameV1>(
        grpc::MethodType.Unary,
        __ServiceName,
        "SingleFrame",
        __Marshaller_UltrasoundCaptureRequestV1,
        __Marshaller_UltrasoundCaptureFrameV1);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::NUHS.Sidecar.UltrasoundCaptureV1Reflection.Descriptor.Services[0]; }
    }

    /// <summary>Client for UltrasoundCaptureServiceV1</summary>
    public partial class UltrasoundCaptureServiceV1Client : grpc::ClientBase<UltrasoundCaptureServiceV1Client>
    {
      /// <summary>Creates a new client for UltrasoundCaptureServiceV1</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public UltrasoundCaptureServiceV1Client(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for UltrasoundCaptureServiceV1 that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public UltrasoundCaptureServiceV1Client(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected UltrasoundCaptureServiceV1Client() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected UltrasoundCaptureServiceV1Client(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual global::NUHS.Sidecar.UltrasoundCaptureSetupResponseV1 Setup(global::NUHS.Sidecar.UltrasoundCaptureSetupRequestV1 request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return Setup(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::NUHS.Sidecar.UltrasoundCaptureSetupResponseV1 Setup(global::NUHS.Sidecar.UltrasoundCaptureSetupRequestV1 request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_Setup, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::NUHS.Sidecar.UltrasoundCaptureSetupResponseV1> SetupAsync(global::NUHS.Sidecar.UltrasoundCaptureSetupRequestV1 request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return SetupAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::NUHS.Sidecar.UltrasoundCaptureSetupResponseV1> SetupAsync(global::NUHS.Sidecar.UltrasoundCaptureSetupRequestV1 request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_Setup, null, options, request);
      }
      public virtual grpc::AsyncServerStreamingCall<global::NUHS.Sidecar.UltrasoundCaptureFrameV1> Stream(global::NUHS.Sidecar.UltrasoundCaptureRequestV1 request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return Stream(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncServerStreamingCall<global::NUHS.Sidecar.UltrasoundCaptureFrameV1> Stream(global::NUHS.Sidecar.UltrasoundCaptureRequestV1 request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncServerStreamingCall(__Method_Stream, null, options, request);
      }
      public virtual global::NUHS.Sidecar.UltrasoundCaptureFrameV1 SingleFrame(global::NUHS.Sidecar.UltrasoundCaptureRequestV1 request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return SingleFrame(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::NUHS.Sidecar.UltrasoundCaptureFrameV1 SingleFrame(global::NUHS.Sidecar.UltrasoundCaptureRequestV1 request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_SingleFrame, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::NUHS.Sidecar.UltrasoundCaptureFrameV1> SingleFrameAsync(global::NUHS.Sidecar.UltrasoundCaptureRequestV1 request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return SingleFrameAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::NUHS.Sidecar.UltrasoundCaptureFrameV1> SingleFrameAsync(global::NUHS.Sidecar.UltrasoundCaptureRequestV1 request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_SingleFrame, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override UltrasoundCaptureServiceV1Client NewInstance(ClientBaseConfiguration configuration)
      {
        return new UltrasoundCaptureServiceV1Client(configuration);
      }
    }

  }
}
#endregion
